image:
  - Visual Studio 2019
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
install:
  - git submodule update --init --recursive
build:
  project: PIMPL.sln
before_build:
  - nuget restore
for:
  -
    matrix:
      only:
        - platform: x86
    test_script:
      - '%APPVEYOR_BUILD_FOLDER%\Build\32\%CONFIGURATION%\PIMPLTests.exe'
  -
    matrix:
      only:
        - platform: x64
    test_script:
      - '%APPVEYOR_BUILD_FOLDER%\Build\64\%CONFIGURATION%\PIMPLTests.exe'
